# Generated by Django 2.2 on 2020-08-12 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='game_name')),
                ('link', models.CharField(max_length=200, verbose_name='game_link')),
                ('status', models.IntegerField(choices=[(0, 'start'), (1, 'running'), (2, 'end')], default=0, verbose_name='game_status')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'games',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='player_name')),
                ('avatar', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'players',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='WaitingRoomMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'not ready'), (1, 'ready'), (2, 'end')], default=0, verbose_name='player waiting room state')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='player')),
            ],
            options={
                'verbose_name': 'room member',
                'verbose_name_plural': 'room member',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='arkserver.Player', verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='game',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='arkserver.Player'),
        ),
    ]
