# Generated by Django 2.2 on 2020-08-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='player_name')),
                ('avatar', models.ImageField(blank=True, default='', null=True, upload_to='avatar')),
            ],
            options={
                'verbose_name': 'players',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='game_name')),
                ('link', models.CharField(max_length=200, verbose_name='game_link')),
                ('status', models.IntegerField(choices=[(0, 'start'), (1, 'running'), (2, 'end')], default=0, verbose_name='game_status')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='arkserver.Player', verbose_name='creator')),
                ('members', models.ManyToManyField(blank=True, null=True, to='arkserver.Player')),
            ],
            options={
                'verbose_name': 'games',
                'verbose_name_plural': 'games',
            },
        ),
    ]
