# Generated by Django 2.2 on 2020-08-06 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='scale')),
            ],
            options={
                'verbose_name': 'scales',
                'verbose_name_plural': 'scales',
            },
        ),
        migrations.CreateModel(
            name='CharacterChoose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'nomal'), (1, 'showed')], default=0, verbose_name='status')),
                ('character_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_one', to='arkserver.Character', verbose_name='scale_one')),
                ('character_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_two', to='arkserver.Character', verbose_name='scale_two')),
            ],
            options={
                'verbose_name': 'tension_scale',
                'verbose_name_plural': 'tension_scale',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_secret', models.CharField(blank=True, max_length=200, null=True, verbose_name='game_password')),
                ('game_name', models.CharField(max_length=200, verbose_name='game_name')),
                ('status', models.IntegerField(choices=[(0, 'start'), (1, 'running'), (2, 'end')], default=0, verbose_name='game_status')),
            ],
            options={
                'verbose_name': 'games',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='player_name')),
                ('nickname', models.CharField(default='', max_length=100, verbose_name='nickname')),
                ('openid', models.CharField(default='', max_length=100, verbose_name='openid')),
                ('game_secret', models.CharField(blank=True, max_length=200, null=True, verbose_name='game_password')),
                ('game_name', models.CharField(max_length=200, verbose_name='game_name')),
                ('inviter_name', models.CharField(max_length=200, verbose_name='creater')),
            ],
            options={
                'verbose_name': 'players',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('player', models.CharField(default='', max_length=500)),
                ('game_secret', models.CharField(default='', max_length=500)),
                ('inviter', models.CharField(default='', max_length=100)),
                ('img', models.FileField(upload_to='result/')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=100, verbose_name='score')),
                ('character_choose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.CharacterChoose')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_score', to='arkserver.Player', verbose_name='voted_person')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorer_score', to='arkserver.Player', verbose_name='voting_person')),
            ],
            options={
                'verbose_name': 'voting',
                'verbose_name_plural': 'voting',
            },
        ),
        migrations.CreateModel(
            name='GameProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100, verbose_name='progress')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='player')),
            ],
            options={
                'verbose_name': 'progress',
                'verbose_name_plural': 'progress',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_game', to='arkserver.Player', verbose_name='creater'),
        ),
        migrations.CreateModel(
            name='FirstScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_score', models.CharField(max_length=20, verbose_name='first score')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='player')),
            ],
            options={
                'verbose_name': 'first score',
                'verbose_name_plural': 'first score',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('love', models.CharField(max_length=500, verbose_name='love')),
                ('add', models.CharField(max_length=500, verbose_name='add')),
                ('ask', models.CharField(max_length=500, verbose_name='ask')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='arkserver.Player', verbose_name='player')),
                ('teammate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammate', to='arkserver.Player', verbose_name='teammate')),
            ],
        ),
        migrations.AddField(
            model_name='characterchoose',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game'),
        ),
        migrations.AddField(
            model_name='characterchoose',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='chooser'),
        ),
    ]
