# Generated by Django 2.2 on 2020-08-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
