# Generated by Django 2.2 on 2020-08-12 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubung3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drainer', models.CharField(default='', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='player')),
            ],
            options={
                'verbose_name': 'Ubung-3',
                'verbose_name_plural': 'Ubung-3',
            },
        ),
        migrations.CreateModel(
            name='Ubung2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='player')),
            ],
            options={
                'verbose_name': 'Ubung-2',
                'verbose_name_plural': 'Ubung-2',
            },
        ),
        migrations.CreateModel(
            name='Ubung1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(default='', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='player')),
            ],
            options={
                'verbose_name': 'Ubung-1',
                'verbose_name_plural': 'Ubung-1',
            },
        ),
    ]
