# Generated by Django 2.2 on 2020-08-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0002_ubung1_ubung2_ubung3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubung4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='author')),
                ('row0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row0', to='arkserver.Player')),
                ('row1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row1', to='arkserver.Player')),
                ('row2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row2', to='arkserver.Player')),
                ('row3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row3', to='arkserver.Player')),
                ('row4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row4', to='arkserver.Player')),
                ('row5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row5', to='arkserver.Player')),
            ],
            options={
                'verbose_name': 'Ubung-4',
                'verbose_name_plural': 'Ubung-4',
            },
        ),
    ]
