# Generated by Django 2.2 on 2020-08-31 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0005_spanscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpanScore',
        ),
    ]
