# Generated by Django 2.2 on 2020-08-31 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0006_delete_spanscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubung5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='arkserver.Player', verbose_name='goal')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='author')),
            ],
            options={
                'verbose_name': 'Ubung-5',
                'verbose_name_plural': 'Ubung-5',
            },
        ),
    ]
