# Generated by Django 2.2 on 2020-09-03 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0008_m2ubung1'),
    ]

    operations = [
        migrations.CreateModel(
            name='M2Ubung2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row1', models.TextField()),
                ('row2', models.TextField()),
                ('row3', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2_goal2', to='arkserver.Player', verbose_name='goal')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='author')),
            ],
            options={
                'verbose_name': 'M2Ubung2',
                'verbose_name_plural': 'M2Ubung2',
            },
        ),
    ]
