# Generated by Django 2.2 on 2020-09-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0009_m2ubung2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubung1',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
