# Generated by Django 2.2 on 2020-09-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0010_ubung1_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubung2',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
