# Generated by Django 2.2 on 2020-09-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0011_ubung2_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubung2',
            name='state',
        ),
        migrations.AddField(
            model_name='ubung3',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
