# Generated by Django 2.2 on 2020-09-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0012_auto_20200923_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubung1',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='player'),
        ),
    ]
