# Generated by Django 2.2 on 2020-09-25 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0013_auto_20200925_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubung3',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='player'),
        ),
    ]
