# Generated by Django 2.2 on 2020-10-09 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0014_auto_20200925_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubung5',
            name='ubung1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubung_1', to='arkserver.Ubung1'),
        ),
        migrations.AddField(
            model_name='ubung5',
            name='ubung3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubung_3', to='arkserver.Ubung3'),
        ),
    ]
