# Generated by Django 2.2 on 2020-10-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0015_auto_20201009_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='m2ubung1',
            name='ubung1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubung_1_for_m2', to='arkserver.Ubung1'),
        ),
        migrations.AddField(
            model_name='m2ubung1',
            name='ubung3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubung_3_for_m2', to='arkserver.Ubung3'),
        ),
    ]
