# Generated by Django 2.2 on 2020-10-28 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0016_auto_20201009_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='author')),
            ],
            options={
                'verbose_name': 'LastStop',
                'verbose_name_plural': 'LastStop',
            },
        ),
    ]
