# Generated by Django 2.2.13 on 2020-11-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0017_laststop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitingroom2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='author')),
            ],
            options={
                'verbose_name': 'Waitingroom2',
                'verbose_name_plural': 'Waitingroom2',
            },
        ),
    ]
