# Generated by Django 2.2.13 on 2020-11-22 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0018_waitingroom2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitingroom2Start',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
            ],
            options={
                'verbose_name': 'Waitingroom2Start',
                'verbose_name_plural': 'Waitingroom2Start',
            },
        ),
    ]
