# Generated by Django 2.2.13 on 2020-11-22 15:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0019_waitingroom2start'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingroom2start',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Waitingroom3Start',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
            ],
            options={
                'verbose_name': 'Waitingroom2Start',
                'verbose_name_plural': 'Waitingroom2Start',
            },
        ),
        migrations.CreateModel(
            name='Waitingroom3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='author')),
            ],
            options={
                'verbose_name': 'Waitingroom2',
                'verbose_name_plural': 'Waitingroom2',
            },
        ),
    ]
