# Generated by Django 2.2.3 on 2019-08-08 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniappTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('union_id', models.CharField(max_length=100)),
                ('open_id', models.CharField(max_length=100)),
                ('session_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('phone', models.CharField(default='', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('password_hex', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WechatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_id', models.CharField(default='', max_length=100)),
                ('nickname', models.CharField(default='', max_length=200)),
                ('head_img', models.CharField(default='', max_length=1000)),
                ('gender', models.IntegerField()),
                ('language', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('province', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.User')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=42)),
                ('open_id', models.CharField(default='', max_length=100)),
                ('channel', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.User')),
            ],
        ),
        migrations.CreateModel(
            name='MiniappUser',
            fields=[
                ('open_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('wechat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.WechatUser')),
            ],
        ),
    ]
