# Generated by Django 2.2.3 on 2019-08-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='open_id',
        ),
        migrations.AlterField(
            model_name='token',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
