# Generated by Django 2.2.3 on 2019-08-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_auto_20190808_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=100)),
                ('access_token', models.CharField(default='', max_length=100)),
                ('expire_time', models.FloatField(default=0)),
                ('openid', models.CharField(default='', max_length=100)),
                ('unionid', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
