# Generated by Django 2.2.3 on 2019-08-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0004_publicaccountuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAccountTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('jsapi_ticket', models.CharField(max_length=200)),
                ('expire_time', models.FloatField(default=0)),
            ],
        ),
    ]
