# Generated by Django 2.1.7 on 2019-08-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0006_auto_20190808_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='access_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
