# Generated by Django 2.2.3 on 2019-08-12 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0007_smscode'),
        ('meta', '0007_auto_20190811_0948'),
    ]

    operations = [
    ]
